# Generated by Django 3.0.4 on 2020-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_incomecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecategories',
            name='currency',
            field=models.CharField(default=1, help_text='Enter a currency code', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomecategories',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
