# Generated by Django 3.0.4 on 2020-03-28 21:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200328_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategories',
            name='name',
            field=models.CharField(help_text='Enter a category name', max_length=200),
        ),
        migrations.CreateModel(
            name='ExpenseCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category name', max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('currency', models.CharField(default='RSD', help_text='Enter a currency code', max_length=3)),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.CategoryType')),
            ],
        ),
    ]
