# Generated by Django 3.0.4 on 2020-03-28 21:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_auto_20200328_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytype',
            options={'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AlterModelOptions(
            name='expensecategories',
            options={'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AlterModelOptions(
            name='incomecategories',
            options={'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.CreateModel(
            name='IncomeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('brut_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_incomeitems_related', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.IncomeCategories')),
            ],
            options={
                'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials')),
            },
        ),
        migrations.CreateModel(
            name='ExpenseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('brut_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_expenseitems_related', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpenseCategories')),
            ],
            options={
                'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials')),
            },
        ),
    ]
