# Generated by Django 3.0.4 on 2020-03-29 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200328_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategories',
            options={'ordering': ['category_type'], 'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AlterModelOptions(
            name='expenseitems',
            options={'ordering': ['date', 'item'], 'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AlterModelOptions(
            name='incomecategories',
            options={'ordering': ['category_type'], 'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AlterModelOptions(
            name='incomeitems',
            options={'ordering': ['date', 'item'], 'permissions': (('can_see_all_financials', 'Show all financials'), ('can_see_own_financials', 'Show own financials'))},
        ),
        migrations.AddField(
            model_name='incomeitems',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='expenseitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 29), null=True),
        ),
        migrations.AlterField(
            model_name='incomeitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 29), null=True),
        ),
    ]
