# Generated by Django 3.0.4 on 2020-04-05 12:34

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0009_auto_20200329_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 5, 12, 34, 6, 508242, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='incomeitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 5, 12, 34, 6, 508242, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='incomeitems',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='SalaryDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('bonus_type', models.CharField(choices=[('F', 'Fixed'), ('R', 'Ratio')], default='F', max_length=1)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpenseCategories')),
            ],
            options={
                'ordering': ['instructor', 'item'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 5, 12, 34, 6, 509238, tzinfo=utc), null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.IncomeCategories')),
            ],
            options={
                'ordering': ['-id', 'date', 'instructor', 'item'],
            },
        ),
    ]
