# Generated by Django 3.0.4 on 2020-04-06 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20200405_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='income_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.IncomeItems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 6, 21, 26, 35, 757326, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='incomeitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 6, 21, 26, 35, 757326, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 26, 35, 758325, tzinfo=utc), null=True),
        ),
    ]
