# Generated by Django 3.0.4 on 2020-04-09 11:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0012_auto_20200406_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 9, 11, 56, 0, 378937, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='expenseitems',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomeitems',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 9, 11, 56, 0, 378937, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 11, 56, 0, 378937, tzinfo=utc), null=True),
        ),
    ]
