# Generated by Django 3.0.4 on 2020-03-24 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_appearance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physical_appearance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physical_appearance',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
