# Generated by Django 3.0.4 on 2020-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200324_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_appearance',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
