# Generated by Django 3.0.4 on 2020-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_physical_appearance_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_appearance',
            name='biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_appearance',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_appearance',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_appearance',
            name='tigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_appearance',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
