# Generated by Django 3.0.4 on 2020-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fa', 'Farsi'), ('fr', 'French'), ('hu', 'Hungarian')], default='m', help_text='Book language', max_length=2),
        ),
    ]
